<?xml version="1.0" encoding="UTF-8"?>
<project name="gaelic" basedir="." default="main">

	<fileset dir="./gd-GB/admin_gd-GB" id="adminfiles">
        <include name="**" />
	</fileset>

	<fileset dir="./gd-GB/api_gd-GB" id="apifiles">
        <include name="**" />
	</fileset>

	<fileset dir="./gd-GB/site_gd-GB" id="sitefiles">
        <include name="**" />
	</fileset>

	<fileset dir="./gd-GB" id="pkgfiles">
        <include name="*.zip" />
        <include name="pkg_gd-GB.xml" />
        <include name="script.php" />
	</fileset>

    <!-- ============================================  -->
    <!-- (DEFAULT) Target: main                        -->
    <!-- ============================================  -->
    <target name="main" description="main target">

        <zip destfile="./gd-GB/admin_gd-GB.zip">
            <fileset refid="adminfiles" />
        </zip>

        <zip destfile="./gd-GB/api_gd-GB.zip">
            <fileset refid="apifiles" />
        </zip>

        <zip destfile="./gd-GB/site_gd-GB.zip">
            <fileset refid="sitefiles" />
        </zip>

        <zip destfile="./pkg_gd-GB.zip">
            <fileset refid="pkgfiles" />
        </zip>

        <exec command="php update-hashes.php pkg_gd-GB.zip updates.xml" passthru="true"/>

    </target>
</project>

