; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

CASSIOPEIA="Teimplaid làrach Cassiopeia"
COM_TEMPLATES_COLORS_FIELDSET_LABEL="Roghainnean Adhartach Datha"
COM_TEMPLATES_SIZES_FIELDSET_LABEL="Roghainnean Adhartach Meud-clò"
TPL_CASSIOPEIA_BACKTOTOP="Air ais gu Barr"
TPL_CASSIOPEIA_BACKTOTOP_LABEL="Ceangal air ais gu barr"
TPL_CASSIOPEIA_BODY_BACKGROUND_COLOR_LABEL="Dath Cùlaibh na Buidhne"
TPL_CASSIOPEIA_BODY_SIZE="Meud-clò na Buidhne (rem)"
TPL_CASSIOPEIA_BODY_TEXT_COLOR_LABEL="Dath Teacsa na Buidhne"
TPL_CASSIOPEIA_BRAND_LABEL="Brand"
TPL_CASSIOPEIA_BUTTON_BACKGROUND_COLOR_LABEL="Dath Cùlaibh a’ Phutan Phrìomh"
TPL_CASSIOPEIA_BUTTON_BACKGROUND_HOVER_COLOR_LABEL="Dath Cùlaibh a’ Phutan Phrìomh (gluasad)"
TPL_CASSIOPEIA_BUTTON_COLOR_LABEL="Dath Teacsa a’ Phutan Phrìomh"
TPL_CASSIOPEIA_BUTTON_HOVER_COLOR_LABEL="Dath Teacsa a’ Phutan Phrìomh (gluasad)"
TPL_CASSIOPEIA_COLORS_LABEL="Cuir an comas Roghainnean Adhartach Datha"
TPL_CASSIOPEIA_COLOR_NAME_ALTERNATIVE="Roghainn Eile"
TPL_CASSIOPEIA_COLOR_NAME_CUSTOM="Gnàthaichte"
TPL_CASSIOPEIA_COLOR_NAME_LABEL="Cuspair Dath"
TPL_CASSIOPEIA_COLOR_NAME_STANDARD="Coitcheann"
TPL_CASSIOPEIA_FLUID="Siùbhlach"
TPL_CASSIOPEIA_FLUID_LABEL="Cruth"
TPL_CASSIOPEIA_FONT_GROUP_LOCAL="Cruth-clò bhon phasgan"
TPL_CASSIOPEIA_FONT_GROUP_WEB="Cruth-clò bhon lìon"
TPL_CASSIOPEIA_FONT_LABEL="Sgeama Chruth-clò"
TPL_CASSIOPEIA_FONT_NOTE_TEXT="Tha cruth-clò an t-siostaim as luaithe ged a dh'fhaodadh gum bi beagan eadar-dhealachaidhean eadar siostaman obrachaidh.<br>Dh’ fhaodadh luchdachadh cruth-clò bho stòran taobh a-muigh a bhith an aghaidh riaghailtean prìobhaideachd ann an cuid de dhùthchannan.<br>Dh’ fhaodadh buaidh a bhith aig cruth-clò a luchdachadh bho phasgan ionadail air coileanadh an làraich agad."
TPL_CASSIOPEIA_FONT_SIZES_LABEL="Cuir an comas Roghainnean Adhartach Meud-clò"
TPL_CASSIOPEIA_FONT_SYSTEM="Cruth-clò an t-siostaim"
TPL_CASSIOPEIA_FONT_SYSTEM_BODY="Staing chruth-clò na buidhne"
TPL_CASSIOPEIA_FONT_SYSTEM_HEADING="Staing chruth-clò nan cinn"
TPL_CASSIOPEIA_FONT_SYSTEM_SELECT="Tagh Cruth-clò an t-siostaim"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ANTIQUE="Seannach"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CLASSICAL="Clasaigeach Daonna"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_CODE="Còd Monospace"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_DIDONE="Didone"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GEOMETRIC="Daonna Cruinn-eòlasach"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_GROTESQUE="Neò-Grotesque"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HANDWRITTEN="Làimhe"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_HUMANIST="Daonna"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_INDUSTRIAL="Gnìomhachais"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_MONOSPACE="Monospace Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_OLDSTYLE="Seann Stoidhle"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_ROUNDED="Caol-shnasach Cruinn"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_SLAB="Slab Serif"
TPL_CASSIOPEIA_FONT_SYSTEM_STACK_SYSTEM_TRANSITIONAL="Eadar-ghluasadach"
TPL_CASSIOPEIA_FOOTER_BACKGROUND_COLOR_LABEL="Dath Cùlaibh a’ Choise"
TPL_CASSIOPEIA_FOOTER_TEXT_COLOR_LABEL="Dath Teacsa a’ Choise"
TPL_CASSIOPEIA_H1_SIZE="Meud-clò H1 (rem)"
TPL_CASSIOPEIA_H2_SIZE="Meud-clò H2 (rem)"
TPL_CASSIOPEIA_H3_SIZE="Meud-clò H3 (rem)"
TPL_CASSIOPEIA_HEADER_BACKGROUND_COLOR_LABEL="Dath Cùlaibh na Bàra-cinn"
TPL_CASSIOPEIA_HEADER_TEXT_COLOR_LABEL="Dath Teacsa na Bàra-cinn"
TPL_CASSIOPEIA_LINK_COLOR_LABEL="Dath nan Ceanglaichean"
TPL_CASSIOPEIA_LINK_HOVER_COLOR_LABEL="Dath nan Ceanglaichean (gluasad)"
TPL_CASSIOPEIA_LOGO_LABEL="Suaicheantas"
TPL_CASSIOPEIA_STATIC="Slaodach"
TPL_CASSIOPEIA_STICKY_LABEL="Ceannard Steigeach"
TPL_CASSIOPEIA_TAGLINE_DESC="Teacsa roghainneil ri shealltainn mar fho-cheann"
TPL_CASSIOPEIA_TAGLINE_LABEL="Tagline"
TPL_CASSIOPEIA_TITLE="Tiotal (roghainn eile an àite suaicheantas)"
TPL_CASSIOPEIA_XML_DESCRIPTION="A’ leantainn air cuspair na h-àrainneachd (Solarflare ann an 1.0, Milkyway ann an 1.5 agus Protostar ann an 3.0), ’s e Cassiopeia teamplaid làraich Joomla stèidhichte air Bootstrap 5."
