; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_BEHAVIOUR_COMPAT="Giùlan - Co-chòrdalachd air ais 5"
PLG_COMPAT_XML_DESCRIPTION="Ma tha thu a’ cleachdadh leudachain nach eil a’ leantainn inbhean còdaidh Joomla an-dràsta, bheir a’ phlugan seo taic do cho-chòrdalachd air ais leis an dreach mhòr roimhe, Joomla 4, nuair a thèid a chur an gnìomh."
