; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_AUTOUPDATE="Ìomhaigh Luath - Brath Inbhe Ùrachaidh Fèin-obrachail Joomla!"
PLG_QUICKICON_AUTOUPDATE_CHECKING="A’ sgrùdadh Ùrachadh Fèin-obrachail &hellip;"
PLG_QUICKICON_AUTOUPDATE_DISABLED="Tha Ùrachaidhean Fèin-obrachail à comas."
PLG_QUICKICON_AUTOUPDATE_ERROR="Inbhe neo-aithnichte airson Ùrachadh Fèin-obrachail &hellip;"
PLG_QUICKICON_AUTOUPDATE_GROUP_DESC="Buidheann a’ phlugain seo (bithear a’ dèanamh coimeas eadar an luach seo agus an luach buidhne a chleachdar ann am modalan <strong>Quick Icons</strong> gus ìomhaighean a chur ris)."
PLG_QUICKICON_AUTOUPDATE_GROUP_LABEL="Buidheann"
PLG_QUICKICON_AUTOUPDATE_OK="Tha Ùrachaidhean Fèin-obrachail an comas."
PLG_QUICKICON_AUTOUPDATE_OUTDATED="Chaidh a’ cheangal airson Ùrachaidhean Fèin-obrachail a bhriseadh."
PLG_QUICKICON_AUTOUPDATE_UNAVAILABLE="Chan eil Ùrachaidhean Fèin-obrachail ri fhaighinn."
PLG_QUICKICON_AUTOUPDATE_XML_DESCRIPTION="Bidh e a’ cumail sùil air inbhe ùrachaidhean fèin-obrachail agus a’ cur fios thugad nuair a thadhlas tu air duilleag Dachaigh a’ Phannal-smachd."
