; Joomla! Project
; (C) 2018 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_SYSTEM_PRIVACYCONSENT="Siostam - Cead Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_BODY="<p>Dh'aontaich an neach-cleachdaidh ri bhith a' stòradh an fhiosrachadh aca le bhith a' cleachdadh an t-seòladh IP <strong>%s</strong></p><p>'S e sruth-chleachdaidh brabhsair an neach-cleachdaidh a bh' ann:<br>%s</p><p>Chaidh am fiosrachadh seo a chlàradh gu fèin-obrachail nuair a chuir an neach-cleachdaidh na mion-fhiosrachadh aca a-steach air an làrach-lìn agus chaidh an cearcall dearbhaidh a thaghadh.</p>"
PLG_SYSTEM_PRIVACYCONSENT_CONSENT="Dh'aontaich neach-cleachdaidh <a href='{accountlink}'>{username}</a> ris a' phoileasaidh prìobhaideachd."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_DESC="Tagh am fios air an liosta no cruthaich fear ùr."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ARTICLE_LABEL="Artaigil Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_ERROR="Tha e èigneachail a bhith ag aontachadh ri Poileasaidh Prìobhaideachd na làraich."
PLG_SYSTEM_PRIVACYCONSENT_FIELD_LABEL="Poileasaidh Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_MENU_ITEM_LABEL="Nì-taice Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_ARTICLE="Artaigil"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_LABEL="Seòrsa Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_FIELD_TYPE_MENU_ITEM="Nì-taice"
PLG_SYSTEM_PRIVACYCONSENT_LABEL="Prìobhaideachd Làrach-lìn"
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT="Le bhith a' clàradh air an làrach-lìn seo agus ag aontachadh ris a' Phoileasaidh Prìobhaideachd tha thu ag aontachadh gum bi am fiosrachadh agad air a stòradh air an làrach-lìn seo."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DESC="Geàrr-chunntas air poileasaidh prìobhaideachd na làraich. Mura h-eil dad sgrìobhte, thèid am brath bunaiteach a chleachdadh."
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_LABEL="Poileasaidh Prìobhaideachd Goirid"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_AGREE="Tha mi ag aontachadh"
PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE="Chan eil mi ag aontachadh"
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DEFAULT="Feuch, dearbhaich gu bheil thu ag aontachadh ri bhith a' stòradh do fhiosrachadh air an làrach-lìn seo le bhith ag aontachadh ris a' phoileasaidh prìobhaideachd."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DESC="Teachdaireachd gnàthaichte airson a shealltainn air ath-stiùireadh. Mura h-eil dad sgrìobhte, thèid am brath bunaiteach a chleachdadh."
PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_LABEL="Teachdaireachd Ath-stiùireadh"
PLG_SYSTEM_PRIVACYCONSENT_SUBJECT="Poileasaidh Prìobhaideachd"
PLG_SYSTEM_PRIVACYCONSENT_XML_DESCRIPTION="Plugan bunaiteach gus cead an neach-cleachdaidh a shireadh ri poileasaidh prìobhaideachd na làraich. Thèid luchd-cleachdaidh a th' ann mar-thà nach eil air cead a thoirt fhathast ath-stiùireadh nuair a logas iad a-steach gus an cunntas aca ùrachadh."
