; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_QUICKICON_AUTOUPDATE="Ìomhaigh Luath - Brath mu Inbhe Ùrachaidh Fèin-obrachail Joomla!"
PLG_QUICKICON_AUTOUPDATE_XML_DESCRIPTION="A’ cumail sùil air inbhe nan ùrachaidhean fèin-obrachail agus a’ toirt brath dhut nuair a thadhlas tu air duilleag Dachaigh a’ Phannal Smachd."
