; Joomla! Project
; (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

PLG_BEHAVIOUR_COMPAT="Giùlan - Co-chòrdalachd air ais 5"
PLG_COMPAT_FIELD_CLASSES_ALIASES_DESCRIPTION="Cuir ris ainmean clas eile airson chlasaichean a chaidh ath-ainmeachadh no gluasad gu àite-ainm ùr."
PLG_COMPAT_FIELD_CLASSES_ALIASES_LABEL="Ainmean Clasaichean Eile"
PLG_COMPAT_FIELD_LEGACY_CLASSES_DESCRIPTION="Cuir an gnìomh an roghainn seo ma tha an leudachan agad a’ cleachdadh chlasaichean a chaidh a chur dheth a-nis agus a chaidh an toirt air falbh à Joomla. Gheibhear na clasaichean sin san phasgan /plugins/behavior/compat/classes/."
PLG_COMPAT_FIELD_LEGACY_CLASSES_LABEL="Gabh a-steach Clasaichean a chaidh a chur dheth"
PLG_COMPAT_FIELD_REMOVED_ASSETS_DESCRIPTION="Cuir an gnìomh an roghainn seo ma tha feum aig an leudachan agad air goireasan a chaidh an toirt air falbh, a dh’adhbhraich eisgeachd. Tha na goireasan seo falamh ach a’ seachnadh na h-eisgeachd."
PLG_COMPAT_FIELD_REMOVED_ASSETS_LABEL="Goireasan air an toirt air falbh"
PLG_COMPAT_XML_DESCRIPTION="Ma tha thu a’ cleachdadh leudachain nach eil a’ leantainn inbhean còdaidh Joomla an-dràsta, bheir a’ phlugan seo taic do cho-chòrdalachd air ais leis an dreach mhòr roimhe, Joomla 5, nuair a thèid a chur an gnìomh."
